---
- name: "KEYCLOAK | Set password for default user '{{ keycloak_default_user }}'"
  ansible.builtin.set_fact:
    keycloak_default_user: "{{ keycloak_default_user | combine(updated_entry, recursive=true) }}"
  vars:
    updated_entry: { 'credentials': [ { 'type': 'password', 'value': '{{ ENV.KEYCLOAK.DEFAULT_USER_PASSWORD }}', 'temporary': false } ] }
  with_dict: "{{ keycloak_default_user }}"

- name: KEYCLOAK | Create default user and set user id
  block:
    - name: "KEYCLOAK | Create default user"
      ansible.builtin.uri:
        url: "{{ keycloak.url.external }}/admin/realms/{{ ENV.KEYCLOAK.REALM }}/users"
        validate_certs: false
        method: POST
        headers:
          authorization: "Bearer {{ keycloak_access_token }}"
        body_format: json
        body: "{{ keycloak_default_user }}"
        status_code: 201, 409
      register: output_post_user
      changed_when: output_post_user.status == 201

    - name: "KEYCLOAK | Get details of '{{ keycloak_default_user.username }}'"
      ansible.builtin.uri:
        url: "{{ keycloak.url.external }}/admin/realms/{{ ENV.KEYCLOAK.REALM }}/users?search={{ keycloak_default_user.username }}"
        validate_certs: false
        method: GET
        headers:
          authorization: "Bearer {{ keycloak_access_token }}"
        status_code: 200
      register: output_get_user

    - name: "KEYCLOAK | Set user id of default user '{{ keycloak_default_user.username }}'"
      ansible.builtin.set_fact:
        __default_user_id: "{{ output_get_user.json[0].id }}"

- name: "KEYCLOAK | Assign realm roles to default users"
  ansible.builtin.include_role:
    name: "eclipse-slm.keycloak_client"
    tasks_from: roles/assign_realm_roles_to_user.yml
  vars:
    _keycloak_realm_name: "{{ ENV.KEYCLOAK.REALM }}"
    _keycloak_access_token: "{{ keycloak_access_token }}"
    _keycloak_user: "{{ keycloak_default_user }}"

- name: "KEYCLOAK | Assign groups to user"
  block:
    - name: "KEYCLOAK | Get details of top level group 'users'"
      ansible.builtin.uri:
        url: "{{ keycloak.url.external }}/admin/realms/{{ ENV.KEYCLOAK.REALM }}/groups?search=users"
        validate_certs: false
        method: GET
        headers:
          authorization: "Bearer {{ keycloak_access_token }}"
        status_code: 200
      register: output_get_group_users

    - name: "KEYCLOAK | Set group id of top level group 'users'"
      ansible.builtin.set_fact:
        __keycloak_users_parent_group_id: "{{ output_get_group_users.json[0].id }}"

    - name: "KEYCLOAK | Create user group for default users"
      ansible.builtin.include_role:
          name: "eclipse-slm.keycloak_client"
          tasks_from: groups/create_child_group.yml
      vars:
          _keycloak_access_token: "{{ keycloak_access_token }}"
          _keycloak_realm_name: "{{ ENV.KEYCLOAK.REALM }}"
          _keycloak_parent_group_id: "{{ __keycloak_users_parent_group_id }}"
          _keycloak_group:
            name: "{{ __default_user_id }}"
            description: "Group for user '{{ keycloak_default_user.username }}'"

    - name: "KEYCLOAK | Get details of users's child group '{{ __default_user_id }}'"
      ansible.builtin.uri:
        url: "{{ keycloak.url.external }}/admin/realms/{{ ENV.KEYCLOAK.REALM }}/groups?search={{ __default_user_id }}"
        validate_certs: false
        method: GET
        headers:
          authorization: "Bearer {{ keycloak_access_token }}"
        status_code: 200
      register: output_get_group_child_user

    - name: "KEYCLOAK | Set group id of users's child group '{{ __default_user_id }}'"
      ansible.builtin.set_fact:
        __keycloak_user_child_group_id: "{{ (output_get_group_child_user.json[0].subGroups | selectattr('name', 'equalto', __default_user_id) | list | first).id }}"

    - name: "KEYCLOAK | Assign user '{{ keycloak_default_user.username }}' to group 'users'"
      ansible.builtin.uri:
        url: "{{ keycloak.url.external }}/admin/realms/{{ ENV.KEYCLOAK.REALM }}/users/{{ __default_user_id }}/groups/{{ __keycloak_user_child_group_id }}"
        validate_certs: false
        method: PUT
        headers:
          authorization: "Bearer {{ keycloak_access_token }}"
        status_code: 204
      register: output_add_user_to_group
